language: java
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
script:
- mvn site
- mvn test
- mvn package -DskipTests
os:
- linux
addons:
  apt:
    packages:
    - oracle-java8-installer
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "target/particles-in-box.jar"
  skip_cleanup: true
  on: 
   tags: true
