language: java
before_install:
- sudo apt-get install javafx
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
script:
- mvn test
- mvn verify
- mvn site
os:
- linux
addons:
  apt:
    packages:
    - oracle-java8-installer
